// Package wire defines the telemetry payload exchanged between the driver app
// (and the simulator) and the ingest API.
//
// It lives at the repo root rather than under api/ because Go scopes an
// internal/ package to the subtree rooted at its parent: api/internal/wire
// would be invisible to sim/. Both producers and the consumer share these
// types, so the JSON contract cannot drift between them.
package wire

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// MaxReadingsPerBatch bounds a single request. A device draining a long offline
// backlog must split it across requests rather than sending one enormous body:
// the batch writer's memory is bounded by (buffer depth x batch size), and an
// unbounded batch would blow through that.
const MaxReadingsPerBatch = 1000

// MaxClockSkewAhead is how far a device's clock may run ahead of the server
// before its readings are rejected.
//
// The asymmetry is deliberate. Readings arriving from the *past* are entirely
// normal — that is exactly what an offline queue produces when a device
// reconnects after hours without signal, and rejecting them would break the
// feature. Readings from the *future* cannot be legitimate and indicate a
// broken device clock, so they are refused before they can corrupt any
// time-ordered aggregate.
const MaxClockSkewAhead = 24 * time.Hour

// Motion states accepted by the server. Kept in sync with the CHECK constraint
// on positions.motion_state — see api/migrations/00001_init.sql.
const (
	MotionStill   = "still"
	MotionWalking = "walking"
	MotionDriving = "driving"
	MotionUnknown = "unknown"
)

// Batch is one upload from a device.
type Batch struct {
	// DeviceID maps to vehicles.external_id. The client never sees or supplies
	// our internal vehicle UUID.
	DeviceID string `json:"device_id"`

	// SentAt is the device's clock at the moment of transmission. Compared
	// against the server's receive time it yields a per-batch clock offset,
	// which is what makes the device's recorded_at values interpretable at all.
	SentAt time.Time `json:"sent_at"`

	Readings []Reading `json:"readings"`
}

// Reading is a single position sample.
//
// Optional fields are pointers rather than values so that "the device did not
// report this" is distinguishable from "the device reported zero". A missing
// speed decoded as 0 would silently turn an unknown sample into a stationary
// one and corrupt every idle-time aggregate downstream — see ADR-001.
type Reading struct {
	// ReadingID is generated by the client as a UUIDv7 and is the primary key.
	// It is what makes replay a no-op: the server inserts ON CONFLICT DO
	// NOTHING, so a batch redelivered after a timeout costs a conflict check.
	ReadingID uuid.UUID `json:"reading_id"`

	// RecordedAt is the device clock at sample time. Not trusted on its own.
	RecordedAt time.Time `json:"recorded_at"`

	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`

	SpeedMPS    *float32 `json:"speed_mps,omitempty"`
	HeadingDeg  *float32 `json:"heading_deg,omitempty"`
	AccuracyM   *float32 `json:"accuracy_m,omitempty"`
	BatteryPct  *int16   `json:"battery_pct,omitempty"`
	MotionState *string  `json:"motion_state,omitempty"`
}

// Rejection names one reading the server refused, and why.
//
// ReadingID is a string rather than a uuid.UUID because a reading can be
// rejected precisely *for* having an unparseable or zero id, and the client
// still needs to be told which entry in its queue to discard.
type Rejection struct {
	ReadingID string `json:"reading_id"`
	Reason    string `json:"reason"`
}

// IngestResponse is returned for an accepted batch.
//
// Partial acceptance is deliberate. Rejecting an entire batch because one
// reading is malformed turns that batch into a poison message: the client's
// durable queue retries it forever and never drains again, permanently breaking
// offline sync for that device. Instead the valid readings are taken and the
// bad ones are named, so the client can drop exactly those and make progress.
type IngestResponse struct {
	Accepted int         `json:"accepted"`
	Rejected []Rejection `json:"rejected,omitempty"`
}

// Validate reports why a reading is unacceptable, or nil if it is fine.
//
// These rules deliberately mirror the CHECK constraints in the positions table.
// That duplication is load-bearing rather than sloppy: the batch writer inserts
// a flush as a single multi-row statement, so one row violating a constraint
// would abort the insert for every other row in that flush. Catching it here
// keeps one bad reading from destroying a batch of five hundred good ones.
func (r Reading) Validate(now time.Time) error {
	if r.ReadingID == uuid.Nil {
		return fmt.Errorf("reading_id is required")
	}
	if r.RecordedAt.IsZero() {
		return fmt.Errorf("recorded_at is required")
	}
	if r.RecordedAt.After(now.Add(MaxClockSkewAhead)) {
		return fmt.Errorf("recorded_at is more than %s in the future", MaxClockSkewAhead)
	}
	if r.Lat < -90 || r.Lat > 90 {
		return fmt.Errorf("lat %v out of range [-90, 90]", r.Lat)
	}
	if r.Lon < -180 || r.Lon > 180 {
		return fmt.Errorf("lon %v out of range [-180, 180]", r.Lon)
	}
	// NaN and Inf decode happily from some JSON producers but cannot be stored
	// as a Postgres double precision, so they have to be caught here.
	if isNotFinite(r.Lat) || isNotFinite(r.Lon) {
		return fmt.Errorf("lat/lon must be finite numbers")
	}
	if r.SpeedMPS != nil && (*r.SpeedMPS < 0 || isNotFinite32(*r.SpeedMPS)) {
		return fmt.Errorf("speed_mps %v must be a finite non-negative number", *r.SpeedMPS)
	}
	if r.HeadingDeg != nil && (*r.HeadingDeg < 0 || *r.HeadingDeg > 360 || isNotFinite32(*r.HeadingDeg)) {
		return fmt.Errorf("heading_deg %v out of range [0, 360]", *r.HeadingDeg)
	}
	if r.AccuracyM != nil && (*r.AccuracyM < 0 || isNotFinite32(*r.AccuracyM)) {
		return fmt.Errorf("accuracy_m %v must be a finite non-negative number", *r.AccuracyM)
	}
	if r.BatteryPct != nil && (*r.BatteryPct < 0 || *r.BatteryPct > 100) {
		return fmt.Errorf("battery_pct %d out of range [0, 100]", *r.BatteryPct)
	}
	if r.MotionState != nil {
		switch *r.MotionState {
		case MotionStill, MotionWalking, MotionDriving, MotionUnknown:
		default:
			return fmt.Errorf("motion_state %q is not recognised", *r.MotionState)
		}
	}
	return nil
}

// Validate checks batch-level invariants. Individual readings are validated
// separately so that they can be rejected individually.
func (b Batch) Validate() error {
	if b.DeviceID == "" {
		return fmt.Errorf("device_id is required")
	}
	if len(b.Readings) == 0 {
		return fmt.Errorf("readings must not be empty")
	}
	if len(b.Readings) > MaxReadingsPerBatch {
		return fmt.Errorf("batch has %d readings, limit is %d", len(b.Readings), MaxReadingsPerBatch)
	}
	return nil
}

// Written out rather than using math.IsNaN/IsInf so the intent reads clearly at
// each call site: x != x is only true for NaN.
func isNotFinite(f float64) bool {
	return f != f || f > 1e308 || f < -1e308
}

func isNotFinite32(f float32) bool {
	return f != f || f > 3.4e38 || f < -3.4e38
}
