-- +goose Up

-- Vehicles are low-volume, so a server-generated random UUID is fine here.
-- gen_random_uuid() is in core Postgres since 13 — no pgcrypto extension needed.
CREATE TABLE vehicles (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id text NOT NULL UNIQUE,
    label       text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- The high-volume table.
--
-- reading_id is generated by the CLIENT as a UUIDv7 and is the primary key.
-- Two consequences, both deliberate:
--
--   1. Idempotency is free. The device may resend a batch after a timeout or a
--      restart, so ingestion uses ON CONFLICT (reading_id) DO NOTHING. Replay
--      costs a conflict check and nothing else.
--   2. UUIDv7 is time-ordered, so inserts land at the right-hand edge of the
--      primary key's B-tree. UUIDv4 would scatter writes across the whole index
--      and dirty far more pages per batch.
--
-- Postgres 17 has no built-in uuidv7() (that arrives in 18), so v7 values are
-- generated in Go. There is no DEFAULT here on purpose: a row without a
-- client-supplied reading_id is a bug, and it should fail loudly.
CREATE TABLE positions (
    reading_id   uuid PRIMARY KEY,
    vehicle_id   uuid NOT NULL REFERENCES vehicles(id),

    -- Two clocks, kept separately and never conflated.
    -- recorded_at is the device's clock and cannot be trusted: phones drift,
    -- and a device replaying an offline backlog reports hours-old times.
    -- received_at is ours. Trip and stop boundaries are never derived from
    -- recorded_at alone.
    recorded_at  timestamptz NOT NULL,
    received_at  timestamptz NOT NULL DEFAULT now(),

    lat          double precision NOT NULL,
    lon          double precision NOT NULL,

    -- NULL means "the device did not report this", which is genuinely different
    -- from zero. Defaulting speed to 0 would silently corrupt idle-time
    -- aggregates by turning unknown readings into stationary ones.
    speed_mps    real,
    heading_deg  real,
    accuracy_m   real,
    battery_pct  smallint,
    motion_state text,

    CONSTRAINT positions_lat_range CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT positions_lon_range CHECK (lon BETWEEN -180 AND 180),
    CONSTRAINT positions_battery_range CHECK (battery_pct IS NULL OR battery_pct BETWEEN 0 AND 100),
    CONSTRAINT positions_heading_range CHECK (heading_deg IS NULL OR heading_deg BETWEEN 0 AND 360),
    -- text + CHECK rather than a Postgres enum: adding a value later is a
    -- one-line migration instead of an ALTER TYPE dance.
    CONSTRAINT positions_motion_state CHECK (
        motion_state IS NULL OR motion_state IN ('still', 'walking', 'driving', 'unknown')
    )
);

-- The workhorse index. Serves "positions for vehicle X between t1 and t2" and,
-- via DISTINCT ON (vehicle_id), "latest position per vehicle" for the live map.
CREATE INDEX positions_vehicle_recorded_idx ON positions (vehicle_id, recorded_at DESC);

-- BRIN on received_at, NOT recorded_at.
--
-- BRIN stores min/max per block range, so it only helps when physical row order
-- correlates with the indexed column. Rows are written in received_at order, so
-- that column correlates. recorded_at does not: the offline queue is designed to
-- drain hours of backlogged readings in a single batch, which drops old
-- timestamps into freshly written pages and destroys the correlation exactly
-- when the feature is working as intended.
--
-- Honest scope: at a few million rows the B-tree above answers every query the
-- product actually makes. This index costs a few KB and earns its keep for
-- retention sweeps and operational "what landed in the last hour" queries.
CREATE INDEX positions_received_brin ON positions USING BRIN (received_at);

-- Trips and stop events are reconciled between two sources — see ADR-002.
-- 'client'  : reported by the device, which has sensor data the server never sees
-- 'derived' : inferred by the server from the position stream
-- Both are stored. Disagreement between them is the interesting signal, so
-- neither overwrites the other.
CREATE TABLE trips (
    id          uuid PRIMARY KEY,
    vehicle_id  uuid NOT NULL REFERENCES vehicles(id),
    source      text NOT NULL,
    started_at  timestamptz NOT NULL,
    ended_at    timestamptz,
    distance_m  double precision NOT NULL DEFAULT 0,
    received_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT trips_source CHECK (source IN ('client', 'derived')),
    CONSTRAINT trips_ended_after_started CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT trips_distance_non_negative CHECK (distance_m >= 0)
);

-- A vehicle can have at most one open trip per source. A partial unique index is
-- how Postgres expresses "unique among rows matching a predicate" — this makes
-- the invariant the database's job rather than the application's.
CREATE UNIQUE INDEX trips_one_open_per_vehicle
    ON trips (vehicle_id, source)
    WHERE ended_at IS NULL;

CREATE INDEX trips_vehicle_started_idx ON trips (vehicle_id, started_at DESC);

CREATE TABLE stop_events (
    id          uuid PRIMARY KEY,
    vehicle_id  uuid NOT NULL REFERENCES vehicles(id),
    trip_id     uuid REFERENCES trips(id),
    source      text NOT NULL,
    arrived_at  timestamptz NOT NULL,
    departed_at timestamptz,
    lat         double precision NOT NULL,
    lon         double precision NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT stop_events_source CHECK (source IN ('client', 'derived')),
    CONSTRAINT stop_events_departed_after_arrived CHECK (departed_at IS NULL OR departed_at >= arrived_at),
    CONSTRAINT stop_events_lat_range CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT stop_events_lon_range CHECK (lon BETWEEN -180 AND 180)
);

CREATE INDEX stop_events_vehicle_arrived_idx ON stop_events (vehicle_id, arrived_at DESC);
CREATE INDEX stop_events_trip_idx ON stop_events (trip_id) WHERE trip_id IS NOT NULL;

-- Reconciliation: which client-reported stop corresponds to which server-derived
-- one, and how far apart they were. A stop_event with no row here is unmatched,
-- and unmatched events on either side are what the reconciliation report is
-- actually about — a client stop the server never saw means the detection
-- thresholds disagree.
CREATE TABLE stop_event_matches (
    client_event_id  uuid NOT NULL REFERENCES stop_events(id) ON DELETE CASCADE,
    derived_event_id uuid NOT NULL REFERENCES stop_events(id) ON DELETE CASCADE,
    delta_seconds    integer NOT NULL,
    delta_meters     double precision NOT NULL,
    matched_at       timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (client_event_id, derived_event_id),
    CONSTRAINT stop_event_matches_distinct CHECK (client_event_id <> derived_event_id)
);

CREATE INDEX stop_event_matches_derived_idx ON stop_event_matches (derived_event_id);

-- +goose Down
DROP TABLE IF EXISTS stop_event_matches;
DROP TABLE IF EXISTS stop_events;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS vehicles;
